keybindings:
  global:
    click:
      <q>: Quit
      <s>: SwitchPage
      <?>: ToggleShowHelp
      <Ctrl-d>: Quit
      <Ctrl-c>: Quit
      <Ctrl-z>: Suspend
  pages:
    Home:
      click:
        <k>: Down
        <j>: Up
      hold:
    Game:
      click:
      hold:
        <h>: Left
        <l>: Right
        <k>: Up
        <j>: Down
    Card:
      click:
        <Enter>: Next
      hold:
