keybindings:
  global:
    click:
      <q>: Quit
      <?>: ToggleShowHelp
      <Ctrl-d>: Quit
      <Ctrl-c>: Quit
      <Ctrl-z>: Suspend
    hold:
  pages:
    Home:
      click:
        <k>: Down
        <j>: Up
        <Enter>: Select
      hold:
    Game:
      click:
      hold:
        <Space>: Up
    Card:
      click:
        <Enter>: Next
      hold:
